# Generated by Django 3.2.23 on 2023-11-16 17:52

import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.IntegerField(choices=[(0, 'Tent'), (1, 'Caravan'), (2, 'Motorhome'), (3, 'Van'), (4, 'Glamping')], default=0)),
                ('pitch_ID', models.CharField(max_length=6, unique=True)),
                ('check_in_time', models.IntegerField(choices=[(3, '3pm'), (3, '3pm')], default=0)),
                ('check_out_time', models.IntegerField(choices=[(11, '11am'), (11, '11am')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pitch_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=15)),
                ('l_name', models.CharField(max_length=25)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in_date', models.DateField(default=datetime.date.today)),
                ('check_out_date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField()),
                ('num_guests', models.IntegerField()),
                ('booking_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='booking.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
