# Generated by Django 3.2.23 on 2023-11-28 14:16

import cloudinary.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.TextField(choices=[('Tent', 'Tent'), ('Caravan', 'Caravan'), ('Motorhome', 'Motorhome'), ('Van', 'Van'), ('Glamping', 'Glamping')], default=0)),
                ('pitch_ID', models.CharField(max_length=6, unique=True)),
                ('check_in_time', models.IntegerField(choices=[(3, '3pm'), (3, '3pm')], default=0)),
                ('check_out_time', models.IntegerField(choices=[(11, '11am'), (11, '11am')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pitch_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in_date', models.DateField(default=datetime.date.today)),
                ('check_out_date', models.DateField(default=datetime.date.today)),
                ('duration', models.IntegerField()),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('booking_price', models.FloatField()),
                ('pitch_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_pitch', to='booking.product', to_field='pitch_ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
