# Generated by Django 3.2.23 on 2023-11-13 17:46

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_type', models.IntegerField(choices=[(0, 'Tent'), (1, 'Caravan'), (2, 'Motorhome'), (3, 'Van'), (4, 'Glamping')], default=0)),
                ('pitch_ID', models.CharField(max_length=6, unique=True)),
                ('check_in_time', models.IntegerField()),
                ('check_out_time', models.IntegerField()),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('available', models.BooleanField()),
                ('pitch_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateTimeField(default=datetime.datetime.now)),
                ('check_out_date', models.DateTimeField(default=datetime.datetime.now)),
                ('num_guests', models.IntegerField()),
                ('booking_price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='booking.product')),
            ],
        ),
    ]
