# Generated by Django 3.2.23 on 2023-11-23 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dates_of_stay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None),
        ),
    ]
