# Generated by Django 3.2.23 on 2023-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='check_in_time',
            field=models.IntegerField(choices=[(3, '3pm'), (3, '3pm')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='check_out_time',
            field=models.IntegerField(choices=[(11, '11am'), (11, '11am')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='pitch_type',
            field=models.IntegerField(choices=[('Tent', 'Tent'), ('Caravan', 'Caravan'), ('Motorhome', 'Motorhome'), ('Van', 'Van'), ('Glamping', 'Glamping')], default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
