# Generated by Django 3.2.23 on 2023-11-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231113_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pitch_type',
            field=models.IntegerField(choices=[(0, 'Tent'), (1, 'Caravan'), (2, 'Motorhome'), (3, 'Van'), (4, 'Glamping')], default=0),
        ),
    ]
